# general configuration
url: http://
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/NDF_Iso.png"
  background: "images/background.jpeg"
  # author will appear under the avatar (optional)
  author: "Fundación Nicaragua Digital"
  # tagline will appear under the title (optional)
  tagline: "Promoviendo las tecnologías digitales en <a href='http://es.wikipedia.org/wiki/Nicaragua'>Nicaragua</a>, para fomentar el desarrollo sostenible."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
